### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by qligier** [DrRoach/DynamicImage#1]
Hey,

Here are some comments about the code, I hope this will help you.

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L91-L95
This should not appear in a library.

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L111
That is not a safe way to protect from a path traversal. Some good lecture: [OWASP](https://www.owasp.org/index.php/Path_Traversal) and [relevant StackExchange topic](https://security.stackexchange.com/q/83147/157374). Also seen in lines 123 and 155.

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L117-L118
It's safer to cast them as integers. More generally, you don't check the content of `$params` (lines 99 and 128).

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L201
It would be easy to extend support to _bmp_, _gif_ or _webp_ images as they are not quite uncommon.

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L245-L273
Why don't you use the builtin function [pathinfo](http://php.net/manual/en/function.pathinfo.php)? `getFilename()` returns an empty string if there is no dot in the input file name and `getExtension()` returns the whole input in the same case.

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L132-L133
That is dangerous because an user can inject strings in `height`, `width`, `filename` and `extension`.

https://github.com/DrRoach/DynamicImage/blob/3ceed2a62b27fa4c0a555d528f796fbc6a9d99bd/DynamicImage.php#L290
[is_writable](http://php.net/manual/en/function.is-writable.php) returns `false` if the path doesn't exist, so the script will never try to create it. Correct condition:
```php
if (is_writable('.') && mkdir('cache'))
// or more simply
if (mkdir('cache'))
```

It would be good to be able to freely choose both `image_directory` and the cache directory because it's a good practice to store images and cache away from the libraries.

Also, have you considered supporting others image libraries? GD [doesn't support color profiles](https://externals.io/message/100214), resulting in bad resized images. Both [Imagick](http://php.net/manual/en/book.imagick.php) and [vips](http://libvips.blogspot.ch/2016/09/introducing-libvips-for-php.html) perform better, faster and use less memory.

Good luck with that :)

**Comment by DrRoach** [comment]
Hi,

Thank you very much for the comments. Most of them have been added to the projects' gitlab tracking board: https://gitlab.com/ryan21030/DynamicImage/issues. Thanks again for the input on these.

The following parts were left out:

- Removing `display_errors` as this is simply a debug feature and isn't usually used.
- Casting the width and height to numbers as this isn't seen as major but will be likely to be picked up in the future.

Future issues:

- Added `imagick` ticket to hopefully improve performance in the future. Needs more research into benchmarks.
